#Deployment of the batch job and a cloud function that triggers this batch job on the basis of the message received from the pub/sub topic
steps:
  # Build the Docker image for the batch job
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/model-train-batch-image:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/model-train-batch-image:latest', './model-train-batch']
    # Push the Docker image with the specific SHA tag to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/model-train-batch-image:$SHORT_SHA']
  # Push the Docker image with the latest tag to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/model-train-batch-image:latest']
  # Deploy the Cloud Function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'adaptive_pipeline_model_function', 
          '--runtime', 'python39',
          '--trigger-topic','adaptive-pipeline-workflow-topic',
          '--source','./adaptive-pipeline-model-function'] 
  # Deploy the Batch job configuration
  # Replace the placeholder with the project ID
  - name: 'bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed "s|gcr.io/YOUR_PROJECT_ID|gcr.io/$PROJECT_ID|" ./batch-config/batch-job-config.yaml.template > ./batch-config/batch-job-config.yaml
  # Submit the Batch job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud batch jobs submit model-training-job \
          --config=./batch-config/batch-job-config.yaml