#Deployment of the batch job and a cloud function that triggers this batch job on the basis of the message received from the pub/sub topic
steps:  
  # Deploy the Cloud Function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'adaptive_pipeline_model_function', 
          '--runtime', 'python39',
          '--trigger-topic','adaptive-pipeline-workflow-topic',
          '--source','./adaptive-pipeline-model-function',
          '--timeout','540s']
