# batch-job-config.yaml

# Define the job specification
job:
  name: "model-training-job"
  region: "us-central1"  # Specify the region where the job should run

  # Define the task groups
  taskGroups:
  - taskSpec:
      # Specify the Docker container to run
      containers:
      - imageUri: "gcr.io/your-project-id/model-train-batch-image:latest"
        commands: []
        options: ""
      maxRunDuration: "3600s"  # Set max duration (optional)
    # Specify the number of tasks to run in parallel
    taskCount: 1
    parallelism: 1

  # Optional: Define job dependencies, environment variables, etc.
  allocationPolicy:
    instances:
    - policy: {}  # Define any specific instance policy if needed
